import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import {
  UIProvider,
  colorModeManager,
  ColorModeScript,
  ThemeConfig,
} from '@yamada-ui/react'
import '@/app/globals.css'

export const metadata: Metadata = {
  title: 'posotto',
  description: 'Generated by create next app',
}
export const fetchCache = 'default-no-store'
export const dynamic = 'force-dynamic'

const config: ThemeConfig = {
  initialColorMode: 'light',
  disableTransitionOnChange: false,
  var: { prefix: 'ui' },
  breakpoint: 'up',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="ja">
        <head>
          <link rel="manifest" href="/manifest.json" />
          <script src="@/app/script.js"  defer></script>
        </head>
        <body>
          <ColorModeScript type="cookie" nonce="testing" />
          <UIProvider
            colorModeManager={{ ...colorModeManager }.cookieStorage}
            config={config}
            // theme={theme} // yamada-uiのバグ？
          >
            {children}
          </UIProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}
