version: '3.8'
services:
  api:
    container_name: api
    build: .
    volumes:
      - ./prisma:/usr/src/app/prisma
    # コンテナのポートとホストのポートを紐づける
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - type: bind
        source: .
        target: /api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/dbname

  db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
