version: '3.8'
services:
  api:
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    build:
      context: .
      target: builder  # マルチステージビルドのビルドステージを指定
    ports:
      - '8000:8000'
    volumes:
      - .:/api  # ソースコードをマウント
    depends_on:
      - db
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://user:password@db:5432/dbname
      PYTHON_PATH: /opt/venv/bin/python3
      SCRIPT_PATH: /api/src/lib/speech_recognition/BERT.py
    command: npm run start:dev

  db:
    image: postgres:12
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
